# Jekyll Configuration
safe: true
markdown: rdiscount
pigments: true
# permalink: pretty
exclude:
    - node_modules
    - Gruntfile.js
    - bower.json
    - package.json
    - bower_components

baseurl: http://masegalab.github.io/curso-d3-basico
page:
    root: 'http://masegalab.github.io/curso-d3-basico'
